name: new_release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.ANDROID_SIGNING_KEY }}
        run: |
          echo "$ENCODED_STRING" > "$RUNNER_TEMP/keystore-b64.txt"
          base64 -d "$RUNNER_TEMP/keystore-b64.txt" > "$RUNNER_TEMP/release-keystore.jks"

      - name: Build release APKs
        env:
          ANDROID_KEYSTORE_PATH: ${{ runner.temp }}/release-keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew assembleRelease 


      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: false
          preserve_order: true
          files: |
            app/build/outputs/apk/release/app-release.apk
          tag_name: "v0.1"
